export const tags = [
  { name: 'HTML/CSS', id: 1 },
  { name: 'Javascript', id: 2 },
  { name: 'PHP', id: 3 },
  { name: 'Typescript', id: 4 },
  { name: 'Angular', id: 5 },
  { name: 'Vue.JS', id: 6 },
  { name: 'React', id: 7 },
  { name: 'Node.JS', id: 8 },
  { name: 'Laravel', id: 9 },
  { name: 'Lumen', id: 10 },
  { name: 'Next.JS' },
  { name: 'Nuxt.JS' },
  { name: 'Electron' },
  { name: 'React Native' },
  { name: 'Vue Native' },
  { name: 'Flutter' },
  { name: 'MySQL' },
  { name: 'PostgreSQL' },
  { name: 'MongoDB' },
  { name: 'Microsoft SQL Server' },
  { name: 'SQLite' },
  { name: 'Cassandra' },
  { name: 'Elasticsearch' },
  { name: 'Redis' },
  { name: 'DynamoDB' },
  { name: 'Symfony' },
  { name: 'Wordpress' },
  { name: 'CodeIgniter' },
  { name: 'CakePHP' },
  { name: 'Zend Framework' },
  { name: 'Cappuccino' },
  { name: 'Prototype' },
  { name: 'Ember.JS' },
  { name: 'Ruby' },
  { name: 'Ruby on Rails' },
  { name: 'Python' },
  { name: 'Go' },
  { name: 'Deno' },
  { name: 'Java' },
  { name: 'C' },
  { name: 'C++' },
  { name: 'C#' },
  { name: 'Objective-C' },
  { name: 'Kotlin' },
  { name: 'Swift' },
  { name: 'SCSS' },
  { name: 'Gatsby' },
  { name: 'Strapi' },
];

export const profiles = [
  { name: 'Almigra' },
  { name: 'Alban' },
  { name: "O''Clock" },
  { name: 'test1' },
];
