export const tags = [
  { name: 'HTML/CSS' },
  { name: 'Javascript' },
  { name: 'PHP' },
  { name: 'Typescript' },
  { name: 'Angular' },
  { name: 'Vue.JS' },
  { name: 'React' },
  { name: 'Node.JS' },
  { name: 'Laravel' },
  { name: 'Lumen' },
  { name: 'Next.JS' },
  { name: 'Nuxt.JS' },
  { name: 'Electron' },
  { name: 'React Native' },
  { name: 'Vue Native' },
  { name: 'Flutter' },
  { name: 'MySQL' },
  { name: 'PostgreSQL' },
  { name: 'MongoDB' },
  { name: 'Microsoft SQL Server' },
  { name: 'SQLite' },
  { name: 'Cassandra' },
  { name: 'Elasticsearch' },
  { name: 'Redis' },
  { name: 'DynamoDB' },
  { name: 'Symfony' },
  { name: 'Wordpress' },
  { name: 'CodeIgniter' },
  { name: 'CakePHP' },
  { name: 'Zend Framework' },
  { name: 'Cappuccino' },
  { name: 'Prototype' },
  { name: 'Ember.JS' },
  { name: 'Ruby' },
  { name: 'Ruby on Rails' },
  { name: 'Python' },
  { name: 'Go' },
  { name: 'Deno' },
  { name: 'Java' },
  { name: 'C' },
  { name: 'C++' },
  { name: 'C#' },
  { name: 'Objective-C' },
  { name: 'Kotlin' },
  { name: 'Swift' },
  { name: 'SCSS' },
  { name: 'Gatsby' },
  { name: 'Strapi' },
];

export const profiles = [
  { name: 'Almigra' },
  { name: 'Alban' },
  { name: "O''Clock" },
  { name: 'test1' },
];
